### PR TITLE
Variables on Docker Compose

### PR DESCRIPTION
**Pull request by allamand**
Hi this pull request may be a respond to issue #31 

It add the ability for docker-compose to be configured with : 
 - a global env file for all projects at path /path/docker-projects/compose-projects.env
 - an additional project specific env file at path /path/to/docker-projects/<project>/.env

I'm very new on python dev, so don't hesitate to comment on the how I do it I can change with no problem.

### CODE REVIEW

**Comment by francescou** [comment]
Hi @allamand thank you for your contribution!

I will try your improvements before merging as soon as possible

**Comment by WTFKr0** [comment]
Thanks i'll try that to

**Comment by francescou** [comment]
Hi @allamand and @WTFKr0 

I've made some improvement in order to support [docker compose environment file](https://docs.docker.com/compose/environment-variables/), see the [relative-paths](https://github.com/francescou/docker-compose-ui/tree/relative-paths) branch.

You can try the example project [env-sample](https://github.com/francescou/docker-compose-ui/tree/c4ebcec71200dfe22a59f9cfac3910c8ebc05260/demo-projects/env-sample) 

```
docker run \
    --name docker-compose-ui \
    -v $(pwd):$(pwd) \
    -w $(pwd) \
    -p 5000:5000 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    francescou/docker-compose-ui:relative-paths
```

do you think this solution would be enought to you? this way we could also guarantee full interoperability with the docker-compose CLI.

**Comment by allamand** [comment]
@francescou, Yes this works. With this i don't have anymore global env for all my projects, but it's manageable to reset them in each .env file project, and it's better has it will works the same with compose-ui or directly with compose.

Perhaps we need a way to see the content of the .env file from the UI ? or it also be useful to mask this info from users don't really have a fix idea on this point.

**Comment by francescou** [comment]
Hello @allamand 
in `francescou/docker-compose-ui:1.1.0` you can see the [docker-compose config](https://docs.docker.com/compose/reference/config/) (which contains env)  in the panel "project details"

thank you for your suggestion!

**Comment by allamand** [comment]
Hello @francescou, very nice work this is great !!

**Comment by francescou** [comment]
I'm closing this pull request since this functionality is provided by the docker compose environment file.

feel free to reopen if necessary

**Pull request closed without merging**
